### ISSUE TITLE
[Bug]: Can't Self Host It With Replit

### ISSUE THREAD

**Issue by MCHAMSTERYT2** [DeveloperJosh/MailHook#39]
I Want To Host It As A Replit Bot But I Can't

**Comment by DeveloperJosh** [comment]
Hello, I'm sorry to hear that it is not working for you, could you show me if there is any errors.

**Comment by MCHAMSTERYT2** [comment]
Exit Status 1

**Comment by MCHAMSTERYT2** [comment]
Can I Invite You To It?

**Comment by DeveloperJosh** [comment]
I will look into this, thank you for letting me know about this bug

**Comment by DeveloperJosh** [comment]
I will not need to join your repl, as i am already making a fix for the bug

**Comment by MCHAMSTERYT2** [comment]
Can You Make The Replit For Me Easier To Use

**Comment by MCHAMSTERYT2** [comment]
By Adding All The Stuff I Need

**Comment by DeveloperJosh** [comment]
You can join our discord server https://discord.gg/EqM7wj5V as i am going to close this ticket
